name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make clang diffutils grep sed coreutils findutils

      - name: Compile the program
        run: \
          mkdir -p build
          cd build
          cmake ..
          make
          cd ..

      - name: Make tests.sh executable
        run: chmod +x ./tests.sh

      - name: Run tests
        run: ./tests.sh